export default {
  currentTrack: {
    trackId: 0,
    trackName: "",
    artistName: "",
    collectionName: "",
    trackTimeMillis: 0,
    primaryGenreName: "",
    trackPrice: 0,
    currency: "",
    collectionViewUrl: "",
    kind: "",
    previewUrl: "",
    artworkUrl30: "",
    artworkUrl60: "",
    artworkUrl100: "",
  },
  nextTrackPath: "",
  previousTrackPath: "",
};
